/** Conviction AI scoring (CONCEPT.md §scoring) — the LLM read that turns a
 *  resolved continuation into the LOGITS the deterministic scorer consumes. After
 *  Arc Gen lands, each open thread has (a) a canonical record of how it actually
 *  moved (the resolved thread log) and (b) the resolutions each seat committed.
 *  This call reads both and emits, per thread, the realized stance (ℓ⁺) and how
 *  much each seat DROVE that shift — WITH REASONING — which the formula then
 *  decomposes (Aumann–Shapley on the Fate/KL) into per-seat Impact + the Fate
 *  house band. So: the AI produces the logits; `lib/game/scoring` scores them.
 *
 *  Pure-ish: one LLM call + deterministic conversion. No store, no React. The AI
 *  emits a probability distribution + per-seat drive (0–1) — shapes it can give
 *  reliably — and this module converts them to the logit / share vectors the
 *  `ThreadAttribution` interface needs. */
import { PREDICTIVE_MODEL } from "@/lib/constants";
import { callGenerate } from "@/lib/ai/api";
import { parseJson } from "@/lib/ai/json";
import type { RoundScore } from "@/lib/game/scoring";

export interface ThreadScoringInput {
  threadId: string;
  /** The open question the thread tracks ("What's my move on…?"). */
  question: string;
  /** Candidate outcomes / actions, in stance order. */
  outcomes: string[];
  /** ℓ⁻ — the round-start stance logits (same order as `outcomes`). */
  logitsBefore: number[];
  /** How the thread ACTUALLY moved in the resolved continuation — the canonical
   *  thread-log prose generated by Arc Gen (ground truth for the realized shift). */
  resolvedLog: string;
  /** What each seat committed on this thread this round. A seat that took NO
   *  action (`acted: false`, conviction 0) still appears — holding is a stance,
   *  scored like any other: restraint that matched the realized landing earns
   *  credit; being overtaken while idle does not. */
  resolutions: { seatId: string; name: string; backed: string; conviction: number; acted: boolean }[];
}

export interface ThreadScoringRead {
  threadId: string;
  /** ℓ⁺ — realized stance logits the resolved log justifies (same order as outcomes). */
  logitsAfter: number[];
  /** Per-seat contribution vector in LOGIT space — feeds `ThreadAttribution.shares`.
   *  Need not sum to Δℓ; the residual becomes the Fate house band. */
  shares: Record<string, number[]>;
  /** Why the thread landed where it did (shown in the score reveal). */
  reasoning: string;
  /** Per-seat one-line attribution (who moved it, and how). */
  perSeat: { seatId: string; reasoning: string }[];
}

const SYSTEM = `You SCORE one round of CONVICTION — a strategy game where seats spend conviction to back what they believe the near future holds, and an engine then GENERATES the continuation. Your job: read how each open thread ACTUALLY resolved in that continuation, and judge how much each seat DROVE that outcome with the resolution it committed.

For EACH thread you are given: the open question, the candidate outcomes (in order), the round-start stance, the CANONICAL resolved log (how the thread really moved — ground truth), and each seat's committed resolution (what it backed, and how hard). A seat may have HELD — committed no card. Holding is itself a stance, NOT an absence: choosing not to push is a decision with consequences, and you score it like any other. Produce:
- realizedProbs: a probability vector over the outcomes (SAME ORDER, sums ~1.0) reflecting where the resolved log left the thread. A decisively resolved thread skews hard; an unresolved/ambiguous one stays flat. Keep each in ~0.02–0.97.
- drive: for EACH seat id, a number in [0,1] — how much THIS seat's stance (action OR deliberate inaction) drove the realized shift. 0 = it had nothing to do with how it landed (or it pushed the other way); 1 = it single-handedly authored the outcome. Seats that backed the realized outcome harder, earlier, or more legibly drove it more. A HELD seat drove the outcome when restraint shaped it — it let a fragile status quo stand, declined to contest a move that then carried, or its forbearance IS why the question landed where it did; a held seat drove ~0 when events simply rolled over its idleness. The drives need NOT sum to 1 — whatever is left over is the world's own (Fate's) doing.
- reasoning: 1 short sentence — why the thread landed where it did.
- perSeat: for each seat id, 1 short clause — its role (drove it / hedged / bet against / held & it held / held & got overtaken / irrelevant).

Be discerning: reward stances — committed OR held — that MATCHED the realized movement; do not credit a seat for an outcome it opposed, and do not credit idleness that was simply overrun. Most threads have a clear primary mover and a thin Fate residual.

Output ONLY JSON: {"threads":[{"threadId":"...","realizedProbs":[...],"drive":{"<seatId>":0.0},"reasoning":"...","perSeat":[{"seatId":"...","reasoning":"..."}]}]}`;

const clamp01 = (x: number) => Math.max(0, Math.min(1, x));
const LOGIT_FLOOR = -12;

/** log of a normalised, floored probability vector → logits (softmax-invertible). */
function probsToLogits(probs: number[]): number[] {
  const safe = probs.map((p) => (Number.isFinite(p) && p > 0 ? p : 1e-6));
  const sum = safe.reduce((a, b) => a + b, 0) || 1;
  return safe.map((p) => Math.max(LOGIT_FLOOR, Math.log(p / sum)));
}

/** Convert one AI thread read into the logit + share vectors the scorer needs. */
function toScoringRead(
  input: ThreadScoringInput,
  raw: { realizedProbs?: unknown; drive?: unknown; reasoning?: unknown; perSeat?: unknown },
): ThreadScoringRead {
  const n = input.outcomes.length;
  const before = input.logitsBefore;

  const probs = Array.isArray(raw.realizedProbs)
    ? raw.realizedProbs.map((p) => (typeof p === "number" ? p : 0))
    : [];
  const logitsAfter =
    probs.length === n ? probsToLogits(probs) : before.slice(); // no usable read → no shift
  const dl = logitsAfter.map((x, k) => x - (before[k] ?? 0)); // Δℓ realized

  // Per-seat drive ∈ [0,1]; if the drives over-explain (sum > 1), scale them down
  // so a non-negative Fate residual remains.
  const driveRaw = (raw.drive ?? {}) as Record<string, unknown>;
  const drive: Record<string, number> = {};
  for (const r of input.resolutions) {
    const d = driveRaw[r.seatId];
    drive[r.seatId] = clamp01(typeof d === "number" ? d : 0);
  }
  const sumDrive = Object.values(drive).reduce((a, b) => a + b, 0);
  const scale = sumDrive > 1 ? 1 / sumDrive : 1;

  const shares: Record<string, number[]> = {};
  // `+ 0` normalises -0 (a zero-drive seat × negative Δℓ) to +0.
  for (const r of input.resolutions) shares[r.seatId] = dl.map((x) => x * drive[r.seatId] * scale + 0);

  const perSeatRaw = Array.isArray(raw.perSeat) ? raw.perSeat : [];
  const perSeat = input.resolutions.map((r) => {
    const found = perSeatRaw.find(
      (p): p is { seatId: string; reasoning: string } =>
        !!p && typeof p === "object" && (p as { seatId?: unknown }).seatId === r.seatId,
    );
    return { seatId: r.seatId, reasoning: typeof found?.reasoning === "string" ? found.reasoning.trim() : "" };
  });

  return {
    threadId: input.threadId,
    logitsAfter,
    shares,
    reasoning: typeof raw.reasoning === "string" ? raw.reasoning.trim() : "",
    perSeat,
  };
}

/** Score a round's threads with the AI. Returns one read per input thread (in
 *  order); a thread the model omits gets a no-shift read (no Impact, no reasoning).
 *  The caller pairs each read with the thread's `logitsBefore` + `volume` to build
 *  `ThreadAttribution[]` for `scoreRound`. */
export async function scoreThreadsWithAI(
  threads: ThreadScoringInput[],
  reasoningBudget = 0,
  /** A short digest of what the round's continuation actually did — shared
   *  context so HELD threads (no per-thread resolved log of their own) can still
   *  be placed: did the world move this question while its owner stood pat? */
  continuation?: string,
): Promise<ThreadScoringRead[]> {
  if (threads.length === 0) return [];

  const user = [
    continuation?.trim() ? `THE ROUND'S CONTINUATION (what actually happened):\n${continuation.trim()}` : "",
    threads
      .map((t, i) => {
        const lines = [
          `THREAD ${i + 1} — id: ${t.threadId}`,
          `Question: ${t.question}`,
          `Outcomes (in order): ${t.outcomes.map((o, k) => `[${k}] ${o}`).join(" · ")}`,
          `Round-start stance (logits): ${t.logitsBefore.map((x) => x.toFixed(2)).join(", ")}`,
          `RESOLVED LOG (how it actually moved): ${t.resolvedLog || "(no recorded movement)"}`,
          "Resolutions:",
          ...t.resolutions.map((r) =>
            r.acted
              ? `  - ${r.name} (${r.seatId}) backed "${r.backed}" with ${r.conviction} conviction`
              : `  - ${r.name} (${r.seatId}) HELD — committed no card (a deliberate non-action stance)`,
          ),
        ];
        return lines.join("\n");
      })
      .join("\n\n"),
  ]
    .filter(Boolean)
    .join("\n\n");

  const raw = await callGenerate(user, SYSTEM, undefined, "scoreThreadsWithAI", PREDICTIVE_MODEL, reasoningBudget);
  const parsed = parseJson(raw, "scoreThreadsWithAI") as { threads?: unknown };
  const reads = Array.isArray(parsed.threads) ? parsed.threads : [];
  const byId = new Map<string, Record<string, unknown>>();
  for (const r of reads) {
    if (r && typeof r === "object" && typeof (r as { threadId?: unknown }).threadId === "string") {
      byId.set((r as { threadId: string }).threadId, r as Record<string, unknown>);
    }
  }
  return threads.map((t) => toScoringRead(t, byId.get(t.threadId) ?? {}));
}

// ── Score reveal — the round's scoring STORY, assembled for the animation ──────
//
// Bundles the whole logic flow into one display-ready object so the reveal needs
// no recomputation: per thread, how much Fate moved and the slice the WORLD owned
// (the Fate house band — out of any player's control), the AI's reasoning, and
// each seat's credit + one-line attribution; plus the round's standings.

export interface ThreadScoreReveal {
  threadId: string;
  /** The open question the thread tracked. */
  question: string;
  /** Total Fate this thread moved this round (v·KL). */
  totalFate: number;
  /** The slice the world owned — Fate OUT of any player's control. */
  houseBand: number;
  /** Why the thread landed where it did (AI). */
  reasoning: string;
  /** Per-seat: signed credit on this thread + the AI's attribution clause. */
  seats: { seatId: string; name: string; color?: string; credit: number; reasoning: string }[];
}

export interface SeatStanding {
  seatId: string;
  name: string;
  color?: string;
  /** Fate this seat moved this round (signed). */
  credit: number;
  /** New running total (Seat.fateImpact after this round). */
  total: number;
  /** 1-based rank by total, after this round. */
  rank: number;
}

export interface RoundScoreReveal {
  roundIndex: number;
  threads: ThreadScoreReveal[];
  /** Per-seat round credit + new standings, ranked by total. */
  standings: SeatStanding[];
  /** Total Fate the round moved. */
  totalFate: number;
  /** Of that, the share the WORLD owned (house band) — clearly surfaced. */
  houseBand: number;
}

/** Assemble the display-ready reveal from the AI reads + the deterministic
 *  RoundScore + seat/thread metadata. Pure — no LLM, no store. This is the single
 *  place the cards → fate → logit-attribution → credit → standings flow is made
 *  explicit, so the animation just renders it. */
export function assembleScoreReveal(args: {
  roundIndex: number;
  reads: ThreadScoringRead[];
  score: RoundScore;
  /** threadId → its open question. */
  questionOf: (threadId: string) => string;
  /** seatId → display name / colour / running total AFTER this round. */
  seatInfo: (seatId: string) => { name: string; color?: string; total: number };
}): RoundScoreReveal {
  const { roundIndex, reads, score, questionOf, seatInfo } = args;
  const readById = new Map(reads.map((r) => [r.threadId, r]));

  const threads: ThreadScoreReveal[] = score.threads.map((ts) => {
    const read = readById.get(ts.threadId);
    const seats = Object.entries(ts.fateCredits).map(([seatId, credit]) => {
      const info = seatInfo(seatId);
      return {
        seatId,
        name: info.name,
        color: info.color,
        credit,
        reasoning: read?.perSeat.find((p) => p.seatId === seatId)?.reasoning ?? "",
      };
    });
    // Movers first (largest |credit|), so the reveal leads with who drove it.
    seats.sort((a, b) => Math.abs(b.credit) - Math.abs(a.credit));
    return {
      threadId: ts.threadId,
      question: questionOf(ts.threadId),
      totalFate: ts.totalFate,
      houseBand: ts.houseBand,
      reasoning: read?.reasoning ?? "",
      seats,
    };
  });
  // Threads that moved the most Fate lead the reveal.
  threads.sort((a, b) => b.totalFate - a.totalFate);

  const standings: SeatStanding[] = Object.entries(score.perSeat)
    .map(([seatId, credit]) => {
      const info = seatInfo(seatId);
      return { seatId, name: info.name, color: info.color, credit, total: info.total, rank: 0 };
    })
    .sort((a, b) => b.total - a.total)
    .map((s, i) => ({ ...s, rank: i + 1 }));

  return { roundIndex, threads, standings, totalFate: score.total, houseBand: score.houseBand };
}
